sudo: required
services:
   - docker

before_install: 

   - docker build -t nitinjain786/docker-react -f Dockerfile.dev .

script:
  
   - docker run nitinjain786/docker-react npm run test -- --coverage



